### ISSUE TITLE
Code runs with warnings

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1716-MVAdrug3waysTab#2]

**Comment by lborke** [comment]
Solved!
see:
https://github.com/QuantLet/QID-1716-MVAdrug3waysTab/commit/9165cdaac7d2dbf002a8f87828785b31aa824b49#diff-1cef0a48231a5a48d22c4e4bef062dd7

I have changed the configuration parameters for this iterative algorithm:
https://stat.ethz.ch/R-manual/R-patched/library/stats/html/glm.control.html

**Comment by lborke** [comment]
The results are still the same as in the MVA book!

**Comment by polarstern** [comment]
> fit = glm.nb(y ~ X1, control=glm.control(maxit=200, epsilon = 1e-6))
Предупреждения
1: In sqrt(1/i) : созданы NaN
2: In sqrt(1/i) : созданы NaN

**Comment by lborke** [comment]
On my system it runs without warnings!
Obviously it depends on the current system (precision, package version, ...)

@TD: can you check it on your system?

@SB: You can try other configurations:
(maxit=100, epsilon = 1e-7) etc..........

**Comment by polarstern** [comment]
> fit = glm.nb(y ~ X1, control=glm.control(maxit=100, epsilon = 1e-7))
Предупреждения
1: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
2: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
---------------------------------------------------------------------------------------------
> fit = glm.nb(y ~ X1, control=glm.control(maxit=200, epsilon = 1e-7))
Предупреждения
1: In sqrt(1/i) : созданы NaN
2: In sqrt(1/i) : созданы NaN

**Comment by lborke** [comment]
Go on....
I have tried 10 times or more ;-)))

**Comment by polarstern** [comment]
Does it really make sense to spend time doing this?

**Comment by lborke** [comment]
After a few minutes and failures you can stop and make a comment about your experience...

**Comment by polarstern** [comment]
> fit = glm.nb(y ~ X1, control=glm.control(maxit=200, epsilon = 1e-2))
Ошибка в while ((it <- it + 1) < limit && abs(del) > eps) { : 
  пропущенное значение, а нужно TRUE/FALSE

Any changing these parameters (maxit, epsilon) gives one of three types of warnings which are described above :-)

**Comment by polarstern** [comment]
So?

**Comment by lborke** [comment]
Create a new datafield in the metainfo.txt and put the warning text into this field:

Code warning: "Your message/warning"

If the Code runs, and sometimes on some machine there are "only" warnings it is ok to be pushed into "Ready".
